export interface Card {
  object: string;
  id: string;
  oracle_id: string;
  multiverse_ids: number[];
  arena_id?: number;
  name: string;
  printed_name?: string;
  lang: string;
  released_at: string;
  uri: string;
  scryfall_uri: string;
  layout: string;
  highres_image: boolean;
  image_status: string;
  image_uris?: {
    small: string;
    normal: string;
    large: string;
    png: string;
    art_crop: string;
    border_crop: string;
  };
  mana_cost?: string;
  cmc?: number;
  type_line: string;
  printed_type_line?: string;
  oracle_text?: string;
  printed_text?: string;
  power?: string;
  toughness?: string;
  colors?: string[];
  color_identity?: string[];
  keywords?: string[];
  produced_mana?: string[];
  all_parts?: Array<{
    object: string;
    id: string;
    component: string;
    name: string;
    type_line: string;
    uri: string;
  }>;
  legalities?: { [key: string]: string };
  games?: string[];
  reserved?: boolean;
  game_changer?: boolean;
  foil?: boolean;
  nonfoil?: boolean;
  finishes?: string[];
  oversized?: boolean;
  promo?: boolean;
  reprint?: boolean;
  variation?: boolean;
  set_id?: string;
  set: string;
  set_name: string;
  set_type?: string;
  set_uri?: string;
  set_search_uri?: string;
  scryfall_set_uri?: string;
  rulings_uri?: string;
  prints_search_uri?: string;
  collector_number?: string;
  digital?: boolean;
  rarity: string;
  flavor_text?: string;
  card_back_id?: string;
  artist?: string;
  artist_ids?: string[];
  illustration_id?: string;
  border_color?: string;
  frame?: string;
  security_stamp?: string;
  full_art?: boolean;
  textless?: boolean;
  booster?: boolean;
  story_spotlight?: boolean;
  edhrec_rank?: number;
  penny_rank?: number;
  promo_types?: string[];
  prices?: { [key: string]: string | null };
  related_uris?: { [key: string]: string };
  purchase_uris?: { [key: string]: string };
}
