services:

  svelte:
    build: .
    container_name: svelte
    command: 'yarn run dev -- --host'
    ports:
      - "5173:5173"
    volumes:
      - '.:/app'
      - /app/node_modules
    environment:
      - NODE_ENV=development